### ISSUE TITLE
Kingswood Knights school emblem

### ISSUE THREAD

**Issue by theWickedWebDev** [theWickedWebDev/blvenyrbdy#1]
Please find and upload the Kingswood Knights High School emblem

**Comment by DJOcean** [comment]
I found a bunch of different images but not quite sure which one is the best. Where should I upload them?

**Comment by theWickedWebDev** [comment]
just put the in the images folder, and git add -a git comit etc...   just pushing one image on a new branch

**Comment by DJOcean** [comment]
done
