### ISSUE TITLE
Need to collect images

### ISSUE THREAD

**Issue by theWickedWebDev** [theWickedWebDev/blvenyrbdy#3]
We can use http://www.shutterstock.com/ or some other service to buy them.  We need to first collect them and discuss whether or not they will work.

**Comment by DJOcean** [comment]
collect what types of images? I dont understand the assignment

**Comment by theWickedWebDev** [comment]
look at ALL the images on the website - we cant use ANY of them.... so find images online that you like and think would be best to use and comment here the links to them and what they are used for

**Comment by DJOcean** [comment]
Oh okay
