### ISSUE TITLE
Calendar Bugs

### ISSUE THREAD

**Issue by theWickedWebDev** [theWickedWebDev/blvenyrbdy#9]
Make font same as rest of site, Fix Arrows, remove branding at bottom of calendar and put entire calendar into the same section as the stuff above it.

**Comment by DJOcean** [comment]
Font was already same

**Comment by DJOcean** [comment]
I think we need to take the arrow buttons as a loss on this one. there just doesnt seem to be a way to make this work

**Comment by theWickedWebDev** [comment]
make the calendar with 100% and 

add more top-margin (or padding - whatever it is) to 'Functional Training Class Schedule $40 - 4 classes'

and change it to read: 'Functional Training Class Schedule'

**Comment by DJOcean** [comment]
k
